create table if not exists public.daily_todo_templates (
    id text primary key,
    owner_email text not null,
    target_email text not null,
    title text not null,
    items_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.daily_todo_records (
    id bigint generated by default as identity primary key,
    template_id text not null,
    target_email text not null,
    date_key text not null,
    week_key text,
    items_json jsonb not null default '[]'::jsonb,
    score integer not null default 0,
    completed_count integer not null default 0,
    total_count integer not null default 0,
    reward_tier text not null default 'low',
    total_score integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.daily_todo_records
    add column if not exists week_key text,
    add column if not exists total_score integer not null default 0;

alter table public.chat_messages
    add column if not exists reactions_json jsonb not null default '[]'::jsonb;

create unique index if not exists daily_todo_records_template_target_date_idx
    on public.daily_todo_records (template_id, target_email, date_key);

create index if not exists daily_todo_records_template_target_week_idx
    on public.daily_todo_records (template_id, target_email, week_key, date_key desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_daily_todo_templates_updated_at on public.daily_todo_templates;
create trigger set_daily_todo_templates_updated_at
before update on public.daily_todo_templates
for each row
execute function public.set_updated_at();

drop trigger if exists set_daily_todo_records_updated_at on public.daily_todo_records;
create trigger set_daily_todo_records_updated_at
before update on public.daily_todo_records
for each row
execute function public.set_updated_at();

insert into public.daily_todo_templates (id, owner_email, target_email, title, items_json)
values (
    'my-love-daily-default',
    'adhammorsy2311@gmail.com',
    'ayaessam487@gmail.com',
    '🌸 Daily Checklist',
    '[
        {"id":"put-medicine-in-bag","text":"Put your medicine in your bag","emoji":"💊","category":"daily","points":10,"order":1,"active":true,"encouragement":"Bag ready, smart girl. You remembered the important stuff 💕"},
        {"id":"eat-breakfast","text":"Eat a good breakfast","emoji":"🥐","category":"daily","points":10,"order":2,"active":true,"encouragement":"Breakfast first, pretty girl. I love seeing you take care of yourself 🌸"},
        {"id":"take-morning-medicine","text":"Take your morning medicine","emoji":"🌞","category":"daily","points":10,"order":3,"active":true,"encouragement":"Morning medicine done. Good job habibti, keep going 💕"},
        {"id":"enjoy-coffee","text":"Enjoy your coffee","emoji":"☕","category":"daily","points":10,"order":4,"active":true,"encouragement":"Coffee time suits you so much, baby. Enjoy every sip ☕💕"},
        {"id":"have-lunch","text":"Have lunch","emoji":"🍱","category":"daily","points":10,"order":5,"active":true,"encouragement":"Lunch checked off. Proud of you for eating properly today 🌸"},
        {"id":"finish-work","text":"Finish your work","emoji":"💼","category":"daily","points":10,"order":6,"active":true,"encouragement":"Work done, superstar. You did amazing today 💼💕"},
        {"id":"head-home-safely","text":"Head home safely","emoji":"🏡","category":"daily","points":10,"order":7,"active":true,"encouragement":"Heading home safely makes my heart calm. Good girl 💕"},
        {"id":"order-food","text":"Order your food","emoji":"🛍️","category":"daily","points":10,"order":8,"active":true,"encouragement":"Food ordered. Love that you took care of dinner, baby 🌸"},
        {"id":"self-care-check","text":"Have one calm self-care moment this week","emoji":"🌷","category":"weekly","points":25,"order":9,"active":true,"encouragement":"That self-care moment matters. You deserve softness and peace 🌷💕"},
        {"id":"water-bottle-refill","text":"Refill your water bottle for tomorrow","emoji":"🍼","category":"daily","points":10,"order":10,"active":true,"encouragement":"Bottle refilled. Future-you is going to love you for that 💧💕"},
        {"id":"go-into-room","text":"Go into your room","emoji":"🚪","category":"daily","points":10,"order":11,"active":true,"encouragement":"Room time. Cozy mode activated for my favorite girl 🚪💕"},
        {"id":"lock-door-securely","text":"Lock the door securely","emoji":"🔒","category":"daily","points":10,"order":12,"active":true,"encouragement":"Door locked. Thank you for keeping yourself safe, habibti 🔒"},
        {"id":"drink-some-water","text":"Drink some water","emoji":"💧","category":"daily","points":10,"order":13,"active":true,"encouragement":"Water check. Good job baby, keep taking care of yourself 💧💕"},
        {"id":"eat-meal","text":"Eat your meal","emoji":"🍽️","category":"daily","points":10,"order":14,"active":true,"encouragement":"Meal finished. Proud of you, pretty girl 🍽️💕"},
        {"id":"take-evening-medicine","text":"Take your evening medicine","emoji":"🌙","category":"daily","points":10,"order":15,"active":true,"encouragement":"Evening medicine done. Perfect, baby 🌙💕"},
        {"id":"double-check-door-locked","text":"Double-check the door is locked","emoji":"🔐","category":"daily","points":10,"order":16,"active":true,"encouragement":"Double-check done. Safe and secure, just how I want you 🔐💕"},
        {"id":"rest-and-sleep","text":"Get some rest and go to sleep","emoji":"😴","category":"daily","points":10,"order":17,"active":true,"encouragement":"Sleep time, my love. Rest well and dream pretty 😴🌸"},
        {"id":"send-a-cute-update","text":"Send a cute little update for extra love points","emoji":"💌","category":"extra","points":15,"order":18,"active":true,"encouragement":"That cute update made my whole day better 💌💕"}
    ]'::jsonb
)
on conflict (id) do update
set owner_email = excluded.owner_email,
    target_email = excluded.target_email,
    title = excluded.title,
    items_json = excluded.items_json,
    updated_at = now();

alter table public.daily_todo_templates enable row level security;
alter table public.daily_todo_records enable row level security;

drop policy if exists "daily_todo_templates_select_allowed" on public.daily_todo_templates;
create policy "daily_todo_templates_select_allowed"
on public.daily_todo_templates
for select
to authenticated
using (
    auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
);

drop policy if exists "daily_todo_templates_owner_insert" on public.daily_todo_templates;
create policy "daily_todo_templates_owner_insert"
on public.daily_todo_templates
for insert
to authenticated
with check (
    auth.email() = owner_email
    and auth.email() = 'adhammorsy2311@gmail.com'
);

drop policy if exists "daily_todo_templates_owner_update" on public.daily_todo_templates;
create policy "daily_todo_templates_owner_update"
on public.daily_todo_templates
for update
to authenticated
using (
    auth.email() = owner_email
    and auth.email() = 'adhammorsy2311@gmail.com'
)
with check (
    auth.email() = owner_email
    and auth.email() = 'adhammorsy2311@gmail.com'
);

drop policy if exists "daily_todo_templates_owner_delete" on public.daily_todo_templates;
create policy "daily_todo_templates_owner_delete"
on public.daily_todo_templates
for delete
to authenticated
using (
    auth.email() = owner_email
    and auth.email() = 'adhammorsy2311@gmail.com'
);

drop policy if exists "daily_todo_records_select_allowed" on public.daily_todo_records;
create policy "daily_todo_records_select_allowed"
on public.daily_todo_records
for select
to authenticated
using (
    auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
    and target_email = 'ayaessam487@gmail.com'
);

drop policy if exists "daily_todo_records_insert_allowed" on public.daily_todo_records;
create policy "daily_todo_records_insert_allowed"
on public.daily_todo_records
for insert
to authenticated
with check (
    target_email = 'ayaessam487@gmail.com'
    and auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
);

drop policy if exists "daily_todo_records_update_allowed" on public.daily_todo_records;
create policy "daily_todo_records_update_allowed"
on public.daily_todo_records
for update
to authenticated
using (
    target_email = 'ayaessam487@gmail.com'
    and auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
)
with check (
    target_email = 'ayaessam487@gmail.com'
    and auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
);

drop policy if exists "daily_todo_records_owner_delete" on public.daily_todo_records;
create policy "daily_todo_records_owner_delete"
on public.daily_todo_records
for delete
to authenticated
using (
    auth.email() = 'adhammorsy2311@gmail.com'
    and target_email = 'ayaessam487@gmail.com'
);

drop policy if exists "chat_messages_update_reactions_allowed" on public.chat_messages;
create policy "chat_messages_update_reactions_allowed"
on public.chat_messages
for update
to authenticated
using (
    auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
)
with check (
    auth.email() in (
        'adhammorsy2311@gmail.com',
        'ayaessam487@gmail.com'
    )
);
