create table if not exists public.daily_todo_templates (
    id text primary key,
    owner_email text not null,
    target_email text not null,
    title text not null,
    items_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.daily_todo_records (
    id bigint generated by default as identity primary key,
    template_id text not null,
    target_email text not null,
    date_key text not null,
    week_key text,
    items_json jsonb not null default '[]'::jsonb,
    score integer not null default 0,
    completed_count integer not null default 0,
    total_count integer not null default 0,
    reward_tier text not null default 'low',
    total_score integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.daily_todo_records
    add column if not exists week_key text,
    add column if not exists total_score integer not null default 0;

alter table public.chat_messages
    add column if not exists reactions_json jsonb not null default '[]'::jsonb;

create unique index if not exists daily_todo_records_template_target_date_idx
    on public.daily_todo_records (template_id, target_email, date_key);

create index if not exists daily_todo_records_template_target_week_idx
    on public.daily_todo_records (template_id, target_email, week_key, date_key desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_daily_todo_templates_updated_at on public.daily_todo_templates;
create trigger set_daily_todo_templates_updated_at
before update on public.daily_todo_templates
for each row
execute function public.set_updated_at();

drop trigger if exists set_daily_todo_records_updated_at on public.daily_todo_records;
create trigger set_daily_todo_records_updated_at
before update on public.daily_todo_records
for each row
execute function public.set_updated_at();

insert into public.daily_todo_templates (id, owner_email, target_email, title, items_json)
values (
    'my-love-daily-default',
    'adhammorsy2311@gmail.com',
    'ayaessam487@gmail.com',
    '🌸 Daily Checklist',
    '[
        {"id":"put-medicine-in-bag","text":"Put your medicine in your bag","emoji":"💊","category":"daily","points":10,"order":1,"active":true},
        {"id":"eat-breakfast","text":"Eat a good breakfast","emoji":"🥐","category":"daily","points":10,"order":2,"active":true},
        {"id":"take-morning-medicine","text":"Take your morning medicine","emoji":"🌞","category":"daily","points":10,"order":3,"active":true},
        {"id":"enjoy-coffee","text":"Enjoy your coffee","emoji":"☕","category":"daily","points":10,"order":4,"active":true},
        {"id":"have-lunch","text":"Have lunch","emoji":"🍱","category":"daily","points":10,"order":5,"active":true},
        {"id":"finish-work","text":"Finish your work","emoji":"💼","category":"daily","points":10,"order":6,"active":true},
        {"id":"head-home-safely","text":"Head home safely","emoji":"🏡","category":"daily","points":10,"order":7,"active":true},
        {"id":"order-food","text":"Order your food","emoji":"🛍️","category":"daily","points":10,"order":8,"active":true},
        {"id":"self-care-check","text":"Have one calm self-care moment this week","emoji":"🌷","category":"weekly","points":25,"order":9,"active":true},
        {"id":"water-bottle-refill","text":"Refill your water bottle for tomorrow","emoji":"🍼","category":"daily","points":10,"order":10,"active":true},
        {"id":"go-into-room","text":"Go into your room","emoji":"🚪","category":"daily","points":10,"order":11,"active":true},
        {"id":"lock-door-securely","text":"Lock the door securely","emoji":"🔒","category":"daily","points":10,"order":12,"active":true},
        {"id":"drink-some-water","text":"Drink some water","emoji":"💧","category":"daily","points":10,"order":13,"active":true},
        {"id":"eat-meal","text":"Eat your meal","emoji":"🍽️","category":"daily","points":10,"order":14,"active":true},
        {"id":"take-evening-medicine","text":"Take your evening medicine","emoji":"🌙","category":"daily","points":10,"order":15,"active":true},
        {"id":"double-check-door-locked","text":"Double-check the door is locked","emoji":"🔐","category":"daily","points":10,"order":16,"active":true},
        {"id":"rest-and-sleep","text":"Get some rest and go to sleep","emoji":"😴","category":"daily","points":10,"order":17,"active":true},
        {"id":"send-a-cute-update","text":"Send a cute little update for extra love points","emoji":"💌","category":"extra","points":15,"order":18,"active":true}
    ]'::jsonb
)
on conflict (id) do update
set owner_email = excluded.owner_email,
    target_email = excluded.target_email,
    title = excluded.title,
    items_json = excluded.items_json,
    updated_at = now();
